REVOKE ALL PRIVILEGES ON * . * FROM 'webuser'@'localhost';

REVOKE GRANT OPTION ON * . * FROM 'webuser'@ 'localhost';

GRANT
SELECT ,
INSERT ,
UPDATE ,
DELETE ,
CREATE ,
DROP ,
INDEX ,
ALTER ,
CREATE VIEW,
SHOW VIEW,
SHOW DATABASES ,
LOCK TABLES ON * . * TO 'webuser'@ 'localhost'
WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 ;

