DROP VIEW "vw_notinpopular" ;COMMIT;
DROP VIEW "vw_btw5d";COMMIT;
DROP VIEW "vw_btw5dbedragen";COMMIT;
DROP VIEW "vw_btwjournaal";COMMIT;
DROP VIEW "vw_btw";COMMIT;
DROP VIEW "vw_btwbedragen1";COMMIT;
DROP VIEW "vw_btwbedragen0";COMMIT;
DROP VIEW "vw_btwbase";COMMIT;
DROP PROCEDURE "proc_partbtw_year_jbedragen";COMMIT;
DROP VIEW "vw_partbtw_year_jbedragen";COMMIT;
DROP PROCEDURE "proc_partbtw_periode_jbedragen";COMMIT;
DROP VIEW "vw_partbtw_periode_jbedragen";COMMIT;
DROP VIEW "vw_periodes";COMMIT;
DROP VIEW "vw_partbtw_year";COMMIT;
DROP VIEW "vw_partbtw_periode";COMMIT;
DROP VIEW "vw_partbtwbedragen";COMMIT;
DROP VIEW "vw_btwtarieven";COMMIT;
DROP VIEW "vw_grootboekkaartExp";COMMIT;
DROP VIEW "vw_grootboekkaart";COMMIT;
DROP VIEW "vw_boekstuk" ;COMMIT;
DROP VIEW "vw_journaalposten";COMMIT;
DROP VIEW "vw_boekregels";COMMIT;
DROP VIEW "vw_btwrubrieken";COMMIT;
DROP VIEW "vw_btwkeys";COMMIT;
DROP VIEW "vw_stamgegevens";COMMIT;
DROP VIEW "vw_dagboeken";COMMIT;
DROP VIEW "vw_grootboekstamsaldo";COMMIT;
DROP VIEW "vw_grootboekstam";COMMIT;
DROP VIEW "vw_boekregelsaldi" ;COMMIT;
DROP VIEW "vw_boekjaar";COMMIT;
